// Code generated by cmd/gen-types. DO NOT EDIT.
//
// Source: server/internal/tick/tick.go
// Regenerate with `just gen-types`.

export const GameVersion = {
  Unknown: 0,
  FH5: 1,
  FH6: 2,
  FM: 3,
} as const;

export type GameVersion = (typeof GameVersion)[keyof typeof GameVersion];

export const PacketVariant = {
  Unknown: 0,
  Sled: 1,
  HorizonDash: 2,
  MotorsportDash: 3,
  Horizon6Dash: 4,
} as const;

export type PacketVariant = (typeof PacketVariant)[keyof typeof PacketVariant];

export type Quad = readonly [number, number, number, number];

export interface TickFrame {
  // Metadata (always populated)
  gv: GameVersion;
  pv: PacketVariant;
  gts: number;
  sts: number;

  // Race state
  race: boolean;
  lap: number;
  pos: number;
  clt: number;
  llt: number;
  blt: number;
  crt: number;

  // Engine
  rpm: number;
  rmx: number;
  rid: number;
  pw: number;
  tq: number;
  bo: number;
  fu: number;

  // Car identity
  co: number;
  cc: number;
  cpi: number;
  dt: number;
  ncy: number;
  cg: number;

  // Smashable collision (FH6-only; 0 on FH5/FM)
  svd: number;
  sm: number;

  // Motion: position / velocity / acceleration (world frame)
  px: number;
  py: number;
  pz: number;
  vx: number;
  vy: number;
  vz: number;
  ax: number;
  ay: number;
  az: number;
  wx: number;
  wy: number;
  wz: number;
  yaw: number;
  pit: number;
  rol: number;
  sp: number;
  di: number;

  // Inputs
  in_a: number;
  in_b: number;
  in_c: number;
  in_h: number;
  g: number;
  st: number;
  dl: number;
  abd: number;

  // Per-wheel arrays (FL, FR, RL, RR)
  tsr: Quad;
  tsa: Quad;
  tcs: Quad;
  tt: Quad;
  wrs: Quad;
  wor: Quad;
  wip: Quad;
  sru: Quad;
  stn: Quad;
  stm: Quad;

  // Enriched fields (derived at ingest, never present on the wire)
  lg: number;
  lng: number;
  tp: number;
  bp: number;
  rp: number;
  gs: boolean;
  ld: number;
}
