/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteImport } from './routes/live'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as StintsStintIdRouteImport } from './routes/stints.$stintId'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as LiveClusterRouteImport } from './routes/live_.cluster'

const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const StintsStintIdRoute = StintsStintIdRouteImport.update({
  id: '/stints/$stintId',
  path: '/stints/$stintId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveClusterRoute = LiveClusterRouteImport.update({
  id: '/live_/cluster',
  path: '/live/cluster',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/live/cluster': typeof LiveClusterRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/stints/$stintId': typeof StintsStintIdRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/live/cluster': typeof LiveClusterRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/stints/$stintId': typeof StintsStintIdRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/live_/cluster': typeof LiveClusterRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/stints/$stintId': typeof StintsStintIdRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live'
    | '/live/cluster'
    | '/sessions/$sessionId'
    | '/stints/$stintId'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live'
    | '/live/cluster'
    | '/sessions/$sessionId'
    | '/stints/$stintId'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/live'
    | '/live_/cluster'
    | '/sessions/$sessionId'
    | '/stints/$stintId'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  LiveClusterRoute: typeof LiveClusterRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  StintsStintIdRoute: typeof StintsStintIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stints/$stintId': {
      id: '/stints/$stintId'
      path: '/stints/$stintId'
      fullPath: '/stints/$stintId'
      preLoaderRoute: typeof StintsStintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live_/cluster': {
      id: '/live_/cluster'
      path: '/live/cluster'
      fullPath: '/live/cluster'
      preLoaderRoute: typeof LiveClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  LiveClusterRoute: LiveClusterRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  StintsStintIdRoute: StintsStintIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
