import { GameVersion, PacketVariant, type Quad, type TickFrame } from "~/types/tick.generated";

const ZERO_QUAD: Quad = [0, 0, 0, 0];

// A complete zeroed TickFrame for tests — no `as` casts needed, so adding a
// field to tick.Tick fails here at compile time instead of silently producing
// tests that exercise a shape the runtime never ships.
export const tickFixture = (overrides: Partial<TickFrame> = {}): TickFrame => ({
  gv: GameVersion.Unknown,
  pv: PacketVariant.Unknown,
  gts: 0,
  sts: 0,
  race: false,
  lap: 0,
  pos: 0,
  clt: 0,
  llt: 0,
  blt: 0,
  crt: 0,
  rpm: 0,
  rmx: 0,
  rid: 0,
  pw: 0,
  tq: 0,
  bo: 0,
  fu: 0,
  co: 0,
  cc: 0,
  cpi: 0,
  dt: 0,
  ncy: 0,
  cg: 0,
  svd: 0,
  sm: 0,
  px: 0,
  py: 0,
  pz: 0,
  vx: 0,
  vy: 0,
  vz: 0,
  ax: 0,
  ay: 0,
  az: 0,
  wx: 0,
  wy: 0,
  wz: 0,
  yaw: 0,
  pit: 0,
  rol: 0,
  sp: 0,
  di: 0,
  in_a: 0,
  in_b: 0,
  in_c: 0,
  in_h: 0,
  g: 0,
  st: 0,
  dl: 0,
  abd: 0,
  tsr: ZERO_QUAD,
  tsa: ZERO_QUAD,
  tcs: ZERO_QUAD,
  tt: ZERO_QUAD,
  wrs: ZERO_QUAD,
  wor: ZERO_QUAD,
  wip: ZERO_QUAD,
  sru: ZERO_QUAD,
  stn: ZERO_QUAD,
  stm: ZERO_QUAD,
  lg: 0,
  lng: 0,
  tp: 0,
  bp: 0,
  rp: 0,
  gs: false,
  ld: 0,
  ...overrides,
});
